# Generated by Django 6.0.2 on 2026-03-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_address_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='+977', max_length=15),
        ),
    ]
